-- DROP DATABASE CC_DB;
-- SHOW VARIABLES LIKE 'SECURE_FILE_PRIV';
-- -- SELECT @@SECURE_FILE_PRIV;
CREATE DATABASE CC_DB;
USE CC_DB;
CREATE TABLE CC_DETAILS(
CLIENT_NUM INT,
CARD_CATEGORY VARCHAR(20),
ANNUAL_FEES	INT,
ACTIVATION_30_DAYS INT,
CUSTOMER_ACQ_COST INT,
WEEK_START_DATE DATE, 
WEEK_NUM VARCHAR(20),
QTR	VARCHAR(10),
CURRENT_YEAR INT,
CREDIT_LIMIT DECIMAL(10,2),
TOTAL_REVOLVING_BAL INT,
TOTAL_TRANS_AMT INT,
TOTAL_TRANS_CT INT,
AVG_UTILIZATION_RATIO DECIMAL(10,3),
USE_CHIP VARCHAR(10),
EXP_TYPE VARCHAR(50),
INTEREST_EARNED DECIMAL(10,3),
DELINQUENT_ACC VARCHAR(5)
);

CREATE TABLE CUST_DETAIL (
CLIENT_NUM INT,
CUSTOMER_AGE INT,
GENDER VARCHAR(5),
DEPENDENT_COUNT	INT,
EDUCATION_LEVEL VARCHAR(50),
MARITAL_STATUS VARCHAR(20),
STATE_CD VARCHAR(50),
ZIPCODE VARCHAR(20),
CAR_OWNER VARCHAR(5),
HOUSE_OWNER VARCHAR(5),
PERSONAL_LOAN VARCHAR(5),
CONTACT VARCHAR(50),	
CUSTOMER_JOB VARCHAR(50),
INCOME INT,
CUST_SATISFACTION_SCORE INT
);
SELECT * FROM CC_DETAILS;


LOAD DATA INFILE
'C:/PROGRAMDATA/MYSQL/MYSQL SERVER 8.0/UPLOADS/CREDIT_CARD.CSV'
INTO TABLE CC_DETAILS
FIELDS TERMINATED BY ','
IGNORE 1 ROWS
(
CLIENT_NUM,
CARD_CATEGORY ,
ANNUAL_FEES	,
ACTIVATION_30_DAYS ,
CUSTOMER_ACQ_COST ,
@WEEK_START_DATE , 
WEEK_NUM ,
QTR	,
CURRENT_YEAR ,
CREDIT_LIMIT ,
TOTAL_REVOLVING_BAL ,
TOTAL_TRANS_AMT ,	
TOTAL_TRANS_CT ,
AVG_UTILIZATION_RATIO ,
USE_CHIP ,
EXP_TYPE ,
INTEREST_EARNED ,
DELINQUENT_ACC 
)
SET
WEEK_START_DATE = STR_TO_DATE(@WEEK_START_DATE, '%D-%M-%Y');

LOAD DATA INFILE
'C:/PROGRAMDATA/MYSQL/MYSQL SERVER 8.0/UPLOADS/CUSTOMER.CSV'
INTO TABLE CUST_DETAIL
FIELDS TERMINATED BY ','
IGNORE 1 ROWS;

SELECT * FROM CC_DETAILS;
SELECT * FROM CUST_DETAIL;




